services:
  db:
    image: postgres:15
    container_name: shoes_db
    environment:
      POSTGRES_DB: #Insira um nome para o banco de dados
      POSTGRES_USER: #Insira um nome para o usuário
      POSTGRES_PASSWORD: #Insira uma senha para o usuário
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
